spring.application.name=hrms
server.port=8082

spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/test?sslMode=VERIFY_IDENTITY&sslEnabled=true
spring.datasource.username=4HV6QBwpu23sbFQ.root

spring.datasource.password=899xisN13JFNjz4x

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect